---
- hosts: garden
  roles:
    - root_key
    - check_mk_client
#    - dachgarten
  vars:
    script_dir: /home/pi/rest_software
    iot_control: /home/pi/iot_control
    script_owner: pi
    script_group: pi
    systemd_owner: root
    systemd_group: root
 
- hosts: stube
  roles:
    - root_key
    - iot_control
    - check_mk_client
    - beamer
    - lircd_stube
  vars:
    iot_control: /home/pi/iot_control
    script_dir: /home/pi/rest_software
    script_owner: pi
    script_group: pi
    systemd_owner: root
    systemd_group: root
    systemd_dir: /lib/systemd/system
