---
- name: copy lircd config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'lircrc', dest: '/etc/lirc/lircrc' }
    - { src: 'RM-ED035.lircd.conf', dest: '/etc/lirc/lircd.conf.d/RM-ED035.lircd.conf' }
    - { src: 'RC-1163.lircd.conf', dest: '/etc/lirc/lircd.conf.d/RC-1163.lircd.conf' }
    - { src: 'tw6000.lircd.conf', dest: '/etc/lirc/lircd.conf.d/tw6000.lircd.conf' }
    - { src: 'ST3002S.lircd.conf', dest: '/etc/lirc/lircd.conf.d/ST3002S.lircd.conf' }
    - { src: 'FBTV235S.lircd.conf', dest: '/etc/lirc/lircd.conf.d/FBTV235S.lircd.conf' }
- name: restart lircd service
  systemd: 
    state: restarted
    name: lircd
- name: install python modules
  pip:
    name:
      - paho-mqtt
      - python-lirc
      - denonavr
    executable: pip3
- name: copy python script
  copy:
    src: mediactrl.py
    dest: "{{ script_dir }}/"
    owner: "{{ script_owner }}"
    group: "{{ script_group }}"
    mode: 0644
- name: copy beamer command wrapper
  copy:
    src: beamer_command.sh
    dest: "{{ script_dir }}/"
    owner: "{{ script_owner }}"
    group: "{{ script_group }}"
    mode: 0755
- name: copy python module mqttw
  copy:
    src: mqttw.py
    dest: "{{ script_dir }}/"
    owner: "{{ script_owner }}"
    group: "{{ script_group }}"
    mode: 0644
- name: copy config file
  copy:
    src: apl19config.json
    dest: "{{ script_dir }}/"
    owner: "{{ script_owner }}"
    group: "{{ script_group }}"
    mode: 0644
- name: start mediactrl service
  systemd: 
    state: restarted
    name: mediactrl
    daemon_reload: yes